### PR TITLE
Adding optForce functions

### PR DESCRIPTION
**Pull request by snmendoz**
[*I added some function to run OptForce in MATLAB*]

**I hereby confirm that I have:**

- [ X] Tested my code on my own machine
- [ X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [ X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by rmtfleming** [comment]
optForceTutorial.m -> tutoroial_optForce.m
See:
https://github.com/rmtfleming/cobratoolbox/blob/cardOptReconX/tutorials/tutorial_template.mlx
I just recently generated that template. Hopefully it helps. We should have had it out there sooner.

**Comment by syarra** [comment]
@snmendoz,

As we closed PR#523 few days ago, I think this PR is not relevant anymore. What do you think? Shall we close it?

**Comment by snmendoz** [comment]
Yes. We should close this PR. Thanks!

**Comment by syarra** [comment]
Closing this PR in favour of PR #523!

**Pull request closed without merging**
