### PR TITLE
Reviewed tutorials and fastLeakTest

### PR DESCRIPTION
**Pull request by almut-heinken**
Reviewed tutorial for sanity checks in model (leak test, etc.) with necessary scripts.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
@almut-heinken, thanks. Is `fastLeakTest.m` a tutorial-specific function, or may you move it to the appropriate `src/` folder?

**Comment by almut-heinken** [comment]
Hi Laurent, no, it is not a tutorial-specific function. I supppose src/reconstruction/modelGeneration would be the best place.

**Comment by almut-heinken** [comment]
I want to move the file, but I still get "Permission to opencobra/cobratoolbox.git denied" when I try to push the commits.

**Comment by almut-heinken** [comment]
fastLeakTest has been moved and more reviewed tutorials have been added.

**Comment by laurentheirendt** [comment]
Closing in favor of PR #796.

PR #773 still contains tutorials `tutorial_modelBorgifier` and `tutorial_paint4net` - they are  conflicting, so edits have been made in the `.mlx` file which wasn't the latest version.

@almut-heinken, may you put in these tutorials as separate PRs? May you also use the [MATLAB.devTools](https://github.com/opencobra/MATLAB.devTools)? Right now, all your commits are on the `develop` branch.

**Pull request closed without merging**
