### PR TITLE
Bug fixing of and addition of features to fastGapFill

### PR DESCRIPTION
**Pull request by wbryant**
Use of fastGapFill in my work has shown up some bugs and some unimplemented features that I have addressed in this branch.  

In brief I have done the following:

* Corrected some minor bugs
* Made all non-essential variables optional, for specification of any combination of variables
* Enabled the use of the weightsPerReaction variable (and the import of weights from a file)
* Enabled the specification of a database with irreversible reactions
* Allowed for a tab-separated text dictionary file
* Allowed for an SBML model as input

All these features can be accessed (and tested) through a new function I have called submitFastGapFill.  In addition to this function I have included the results from the default (test) datafiles; these can be viewed without running prepareFastGapFill (which takes many hours) and fastGapFill (which can take up to an hour).

Cheers,
Will.

### CODE REVIEW

**Comment by huldash** [comment]
Dear Will,

Thank you for your contributions to the code. Can you please use your code to prepare a test function for fastGapFill in cobratoolbox/testing? It would be of great help for future updates.

Best,
Hulda

**Comment by wbryant** [comment]
Hi Hulda,

Thanks for merging my proposed changes!  I shall write a test function for it soon.

Does MATLAB/Cobratoolbox have a particular preferred format for tests?  Or should I just pick one of the test files from the `cobratoolbox/testing` folder and use that as a template?

Cheers,

Will.

**Comment by huldash** [comment]
You can just use one of the existing tests as a template.

Thank you,
Hulda

**Comment by wbryant** [comment]
Hi Hulda,

I know it has been a while so I hope you are still working on the 
Cobratoolbox but have just completed a test function for FastGapFill and 
created a pull request ('Fix FastGapFill bugs and add test function' 
#206) and wanted to let you know.

Please let me know if anything else is required.

Also it failed a check with the message 'Build finished', but I am not 
sure how to address this.

Cheers,

Will.

**Pull request merged**
