### PR TITLE
ctype field needs to be a row vector in cplex.

### PR DESCRIPTION
**Pull request by tpfau**
**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [contributing](https://github.com/opencobra/cobratoolbox/blob/master/.github/CONTRIBUTING.md) document
- [X] Followed the [code styleguide](https://github.com/opencobra/cobratoolbox/blob/master/.github/CONTRIBUTING.md#code-styleguide)
- [X] Checked to ensure there aren't other open [Pull Requests](https://github.com/opencobra/cobratoolbox/pulls) for the same update/change
- [X] Written platform-independent code
- [X] Used `pwd` to get the current directory
- [X] Used `filesep` for paths (e.g., `['myPath' filesep 'myFile.m']`)
- [X] Made sure that computational results are reproducible

### Errors/fixes (with reference to eventual open issues)

e.g. OptKnock produced a row vector for the vartype, which was previously transposed in the cplex setup. The current code ensures, that transposition only happens if the ctype vector would otherwise have the wrong orientation.

###  Tests tailored to test the PR

No specific test for this PR.

### CODE REVIEW

**Comment by laurentheirendt** [comment]
I will add a quick test.

**Comment by tpfau** [comment]
The problem is: you can't test it on 2016b, since Matlab segfaults with ibm_cplex on 2016b, so an explicit test will always fail on 2016b...

**Comment by laurentheirendt** [comment]
Let's see ...

**Comment by laurentheirendt** [comment]
Note: the `ibm_cplex` interface is tested for `R2014b` and `R2015b` (but not for `R2016b`).

**Comment by syarra** [comment]
Good job @tpfau and @laurentheirendt! :1st_place_medal:

**Pull request merged**
