### PR TITLE
A modification on extractGPRs 

### PR DESCRIPTION
**Pull request by Ojami**
subfunction **extractGPRs** of **createTissueSpecificModel** has been replaced with a more sufficient script to reduce CPU-time of the old function.

### CODE REVIEW

**Comment by Ojami** [comment]
Function called testExactGRPs has been created upon request with some tests on some COBRA models, validating the output results and comparing cpu-time, 

[https://github.com/Ojami/cobratoolbox/blob/Ojami-patch-3/testing/testExtractGPRs.m](url)

**Comment by Ojami** [comment]
[cobratoolbox/testing/testExtractGPRs.m](url)

**Comment by Ojami** [comment]
[cobratoolbox/testing/testExtractGPRs.m](url)

**Comment by rmtfleming** [comment]
@Ojami please could you check what is blocking the merge here and edit your pull request?

**Comment by syarra** [comment]
@Ojami is reporting the following CPU usage:
````
IMPROVEMENTS: Compare with two COBRA models Recon1 and iOJ1366 resulted in two following outputs:
1- CPU-time of the new algorithm for iOJ1366 = 1.835656 compared to the old one 43.800403 seconds,
2- CPU-time of the new algorithm for Recon1 = 3.454554 compared to the old one 247.569950 seconds,
Results of two methods (ParsedGPR and corrRxn) are the same to each other.
````

**Pull request closed without merging**
