### PR TITLE
Template for a main function

### PR DESCRIPTION
**Pull request by shjchan**
I think for the infrastructure we have for parsing inputs and parameters now, we can have a template like this for writing main functions that handle input and/or cobratoolbox and/or solver-specific parameters consistently. This should be general enough and can save quite some time.
Suggestions and comments are welcome. 
One thing is that I am not sure where this file should go.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

### CODE REVIEW

**Comment by rmtfleming** [comment]
@Gpreciat 
please look into this 
https://prince.lcsb.uni.lu/jenkins/job/COBRAToolbox-pr-auto-windows10/MATLAB_VER=R2017b,label=prince-slave-windows10-01/1445/console
19:31:16 testPrintInRecon3Dmap failed!
19:31:16 Reason:
19:31:16 Error using testPrintInRecon3Dmap (line 29)
19:31:16 Reference map does not match.

**Comment by rmtfleming** [comment]
@laurentheirendt 
please can you check that matlab connector is running on the windows machines? The answer to this post shows how to do that.
https://uk.mathworks.com/matlabcentral/answers/95444-why-am-i-unable-to-connect-matlab-mobile-to-the-matlab-connector-running-on-my-computer

**Comment by laurentheirendt** [comment]
I am not sure I understand. Why would there be a need for a MATLAB connector on MATLAB mobile? 

This test is failing at line 29 because of a line break that is different on Windows. For instance:
```
>> testMap(2)

ans =

  1×1 cell array

    {'	R_10FTHF5GLUtl	8.0000004	#800000←'}

>> newMap(2)

ans =

  1×1 cell array

    {'	R_10FTHF5GLUtl	8.0000004	#800000'}

```

**Comment by rmtfleming** [comment]
Accepting pr as the windows issue is with other code.

**Pull request merged**
