### PR TITLE
Speeding up single array version of findNeighborhoodRxns

### PR DESCRIPTION
**Pull request by akaviaLab**
This should speed up neighborhood rxns when the desired output is a single array.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
@akaviaLab, may you fix the issue with `testNeighborRxn2data`? Thanks.

**Comment by akaviaLab** [comment]
Why does neighborRxn2data load rxn.mat?
This is a small matrix that contains 16 reactions from what looks like RECON 2, and then the function uses this preloaded file.

**Comment by akaviaLab** [comment]
How can I retrigger build and testing?

**Comment by laurentheirendt** [comment]
By closing and re-opening the PR.

**Comment by akaviaLab** [comment]
I closed and reopened, and the build was not triggered. Trying again.

**Comment by akaviaLab** [comment]
ping @laurentheirendt

**Comment by laurentheirendt** [comment]
Thanks @akaviaLab 👍

**Pull request merged**
