### PR TITLE
Model Manipulation tutorial with Thomas modifications and with template

### PR DESCRIPTION
**Pull request by vlasovv**
[*Please include a short description of enhancement here*]

**I hereby confirm that I have:**

- [ ] Tested my code on my own machine
- [ ] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [ ] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by rmtfleming** [comment]
Some of those warnings are technical, related to setup of matlab, rather than cobra. Can you iron them out please?

**Comment by tpfau** [comment]
the simplest is to set "warning off MATLAB:subscripting:noSubscriptsSpecified" at the beginning of the tutorial

**Comment by laurentheirendt** [comment]
@vlasovv, may you try to solve these conflicts? Running `contribute` and selecting option `[2]` should do it. Alternatively, you may also submit a new PR.

Please ping me if you need help. Thanks!

**Comment by vlasovv** [comment]
@laurentheirendt  Yes I all the time have some errors

**Comment by vlasovv** [comment]
Error using submitContribution (line 167)
dev>   [submitContribution] Your commit message cannot be set. (Error)

Error in contribute (line 119)
                    submitContribution(reply);

**Pull request closed without merging**
