### PR TITLE
Adding Direct IO from the BiGG Database

### PR DESCRIPTION
**Pull request by tpfau**
Fixing a bug in readCbModel (not sure how this ever worked in so many tests 'sigh') and adding IO to read/write directly from the BiGG database. 

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
@tpfau, do you have any test for this?

**Comment by tpfau** [comment]
I can write one.

**Comment by laurentheirendt** [comment]
@tpfau, do you mind looking at why the CI is failing here? Thanks!

**Comment by tpfau** [comment]
Because the fix to the rules field generation from generateRules from #920 is not in. 
Thus .mat files are not correctly read by readCbModel if they do not contain a rules field, as it is generated with wrong dimensions.

**Comment by tpfau** [comment]
Closing till #920 is in.

**Pull request merged**
