### PR TITLE
A little modification of the script "sampleScatterMatrix.m" for running smoothly in Matlab 2016b on win10

### PR DESCRIPTION
**Pull request by xiaohuihui97**
*Delete a space in line 137 of the script "sampleScatterMatrix.m", so that it can run smoothly in Matlab 2016b on win10.*

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Thanks @xiaohuihui97. 👍 

*Note*: Your fork is not up-to-date and far behind. I recommend you deleting your fork and forking again, and then use the [MATLAB.devTools](https://github.com/opencobra/MATLAB.devTools).

**Comment by laurentheirendt** [comment]
Closing and re-opening to re-trigger CI.

**Comment by laurentheirendt** [comment]
Closing and re-opening to re-trigger CI.

**Comment by xiaohuihui97** [comment]
OK, I will do it. Thank you.@laurentheirendt

**Comment by laurentheirendt** [comment]
Thanks @xiaohuihui97 🎉

**Pull request merged**
