### PR TITLE
preprocessing expression data

### PR DESCRIPTION
**Pull request by arichelle**
Folder containing scripts to map expression data to model reactions as it is no longer included in createTissueSpecificModel.
The parsing of GPR rules uses the GPR parser of @tpfau

### CODE REVIEW

**Comment by tpfau** [comment]
Hi Anne,
Could you cherry-pick my parser classes such that they are part of this pr, because at the moment, this code is not part of the Toolbox, and therefore this pr would fail.

**Comment by arichelle** [comment]
Done !

**Comment by tpfau** [comment]
Well, ok I actually meant cherry-pick not copy ^^
i.e. git cherry-pick a0ad906919d0a6f6583828dc91ab52c673b980cb
which would have added my commit to your commit. 
Anyways I'll have to add docu to my code.

**Comment by arichelle** [comment]
Sorry let me know if you want that I remove the folder and try to make it the right way ?

**Comment by tpfau** [comment]
No problem. Actually, I just check some things and noticed that there seems to be a bug in the parser....
I'll have to investigate that. :(

**Comment by laurentheirendt** [comment]
@tpfau, let me know how I can help.

**Comment by tpfau** [comment]
I updated the files adding documentation, even though I'm not sure how best to document classes... 
If you could cherry pick  	baa74c4 , 5a2f111 and f6ef08a on top of the current pr, that would be great

**Comment by laurentheirendt** [comment]
Thanks @arichelle and @tpfau! Great team work! 👍

**Pull request merged**
