### PR TITLE
Introduction of Additional Constraints and Variables

### PR DESCRIPTION
**Pull request by tpfau**
This PR introduces additional constraints and variables in a consistent manner.
Current coupling approaches are converted to use this approach.
It also adjusts several methods allowing them to take these constraints/variables into account.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by tpfau** [comment]
I created a PR for the tutorial on COBRA.tutorials and will update the submodules in this PR once the tutorial is merged. 
I also added additional convenience functions for Variables/constraints in order to allow an easier updating/manipulation and added a test function (based on the tutorial).

**Comment by tpfau** [comment]
I've seen that. This is nothing that my code is touching as it is a pure cplex methodology. 
I'll restart the CI to see if this error keeps popping up. If not, I think we will have to change this test.

**Comment by laurentheirendt** [comment]
Nice job, @tpfau 👍 ⚽️

**Comment by almut-heinken** [comment]
Hi @tpfau @laurentheirendt ,
the change in the coupleRxnList2Rxn function results in different model structures. Currently, the fastFVA function is still looking for the A matrix with coupling constraints, so we are unable to use it. Could you please also adapt fastFVA? 
Best,
Almut and @Fede-edef

**Pull request merged**
