### PR TITLE
CBT defaults are more stringent than solvers defaults

### PR DESCRIPTION
**Pull request by marouenbg**
*Please include a short description of enhancement here*
-feaopt and tolopt are set to 1e-9 which considerably slows solving of medium to large models.
-cplex defaults are set to 1e-6 (EPOPT and EPRHS)
https://tomopt.com/docs/cplexug/tomlab_cplex014.php

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- []x Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [] with [X] to check the box)*

### CODE REVIEW

**Comment by tpfau** [comment]
Changing the solver parameters will make earlier external code that relies on them being at these values invalid or change its results. I agree that we should more clearly communicate our choices for the default parameter values, but I would keep them how they are.
If someone needs less precise solutions for large models he/she can simply use changeCobraSolverParams and set them accordingly for his analysis scripts.

**Comment by rmtfleming** [comment]
Indeed, changeCobraSolverParams is the way to go instead.

**Comment by marouenbg** [comment]
this is up to you, I would expect the CBT defaults to match the solver default. These values are consistent across gurobi, ibm cplex and tomlab. Here it is 1000x smaller, users would have infeasibilites like I did, without knowing where this is coming from.

http://www.gurobi.com/documentation/6.0/refman/optimalitytol.html#parameter:OptimalityTol

**Comment by marouenbg** [comment]
from the CPLEX manual
https://www.ibm.com/support/knowledgecenter/en/SS9UKU_12.4.0/com.ibm.cplex.zos.help/Parameters/topics/EpRHS.html

Any number from 1e-9 to 1e-1; default: 1e-06.

If the feasibility tolerance is set too low, CPLEX® may falsely conclude that a problem is infeasible.

**Pull request closed without merging**
