### PR TITLE
Adding OPTI solvers for solving LPs in Cobra

### PR DESCRIPTION
**Pull request by shyamsrinivasan**
Changes incorporated into cobra to enable it to access a wider variety of open source solvers to solve LPs. The current addition adds supported solvers from the opti suite of solvers for matlab. In all cases opti acts as a wrapper around the select solver.
Solvers: CLP and SCIP (other solvers were already supported in cobra)
changes are restricted to solveCobraLP, changeCobraSolver,getCobraSolverParams (adding 2 new parameters for opti)
Also included tutorials on using opti with cobra

### CODE REVIEW

**Comment by rmtfleming** [comment]
This cannot be merged automatically. Was your starting point the code in https://github.com/opencobra/cobratoolbox
or
https://github.com/rmtfleming/cobratoolbox

**Comment by shyamsrinivasan** [comment]
The starting point was rmtfleming/cobratoolbox.
I am trying to see if updating my master would solve this issue

**Comment by shyamsrinivasan** [comment]
Merging opencobra/cobratoolbox/master to my fork did not solve this issue.
From what I see the changes are mutually exclusive (changes in opencobra/cobratoolbox are extensively associated with solely COBRA functions and their help files. None of these files have been modified from the purpose of adding OPTI)
What else do you recommend?

**Comment by rmtfleming** [comment]
git clone https://github.com/opencobra/cobratoolbox
then line by line add your changes to it.

**Comment by shyamsrinivasan** [comment]
So if I understand this correctly, I will have a clone (not a fork) from opencobra/cobratoolbox and will be adding my changes to this copy. Is that correct?

**Comment by rmtfleming** [comment]
I deleted https://github.com/rmtfleming/cobratoolbox to avoid any further issues like this.

Yes, git clone https://github.com/opencobra/cobratoolbox then make your changes to that version.

It is just to sensitive a section of code to take any chances with it.

**Pull request closed without merging**
