### PR TITLE
Fixing errors when creating missing fields

### PR DESCRIPTION
**Pull request by akaviaLab**
Trying to add reactions to a model that has genes, but no gene rules leads to errors (invalid models), as did adding exchange reactions to a model (problem with subSystem definition). I've corrected the error and modified the test to fail without my corrections.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by akaviaLab** [comment]
I've been looking into why testExtractConditionSpecificModel fails
- The reference model has Exchange reactions in a different manner {'Exchange'} than the result {{'Exchange'}}. I've fixed that by changing the reference model (will be a separate commit)
- isSameCobraModel does not check the subSystems, because they are cells within cells. Should this be opened as a separate bug?

**Comment by laurentheirendt** [comment]
@akaviaLab, is there any way that you can fix that?

**Comment by akaviaLab** [comment]
Hi Laurent,
I've added a different version of the reference model, and the tests pass.

As for isSameCobraModel not checking subSystems, should that be a separate issue? Should it even be fixed (a lot of scripts are using isequal, which seems to work)?
One way of fixing it is changing subSystems not to be cells within cell, but I'm not sure why that is even the case. Is this so reactions can have more than one subSystem?

**Comment by laurentheirendt** [comment]
Thanks @akaviaLab 👍

**Comment by tpfau** [comment]
> 
> 
> Hi Laurent,
> I've added a different version of the reference model, and the tests pass.
> 
> As for isSameCobraModel not checking subSystems, should that be a separate issue? Should it even be fixed (a lot of scripts are using isequal, which seems to work)?
> One way of fixing it is changing subSystems not to be cells within cell, but I'm not sure why that is even the case. Is this so reactions can have more than one subSystem?

That's exactly it.
By convention, e.g. in SBML subsystems are represented by the groups extension. And thus a reaction can be part of multiple subsystem "groups".
It also makes a lot of sense, as e.g. we currently have things like "Glycolysis/Gluconeogenesis" as a single pathway, while this are in fact different pathways which have multiple reactions in common, but also have reactions which separate them (something thats not well represented by current models).

**Pull request merged**
