### PR TITLE
Adressed constraints that may cause infeasibilities in mgPipe

### PR DESCRIPTION
**Pull request by almut-heinken**
Edited constraints in mgPipe workflows to prevent infeasibilities in certain models.
Removed unnecessary outputs.
Edited shadow price simulations to prevent out of memory errors.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by rmtfleming** [comment]
https://prince.lcsb.uni.lu/jenkins/job/COBRAToolbox-pr-auto-linux/MATLAB_VER=R2016b,label=prince-slave-linux-01/3101/console

gives 

12:42:25 The following tests failed:
12:42:25 testMgPipe.m
12:42:25 
12:42:25 The reasons were as follows:
12:42:25 ------------------------------------------------
12:42:25 testMgPipe.m:
12:42:25 Error using initMgPipe
12:42:25 Too many output arguments.
12:42:25 Error in testMgPipe (line 70)
12:42:25 init = initMgPipe(modPath, CBTDIR, resPath, dietFilePath, abunFilePath, indInfoFilePath, objre, figForm, numWorkers, autoFix, compMod, rDiet, extSolve, fvaType, autorun);
12:42:25 ------------------------------------------------

**Comment by PejmanS** [comment]
Hi
I had this error too.
You should run initMgPipe manually, not by startMgPipe.

**Comment by almut-heinken** [comment]
I think that testMgPipe should be edited and the outputs of initMgPipe removed. As far as I can tell, they serve no purpose.

**Comment by rmtfleming** [comment]
On linux, after line 70, I get:

>> testMgPipe
 > Models will be read from: /home/rfleming/work/sbgCloud/code/fork-cobratoolbox/test/models/mat/
 > Results will be stored in: /home/rfleming/work/sbgCloud/code/fork-cobratoolbox/.tmp/
 > Microbiome Toolbox pipeline initialized successfully.

Line 70 of testMgPipe is 
% input checker
init = initMgPipe(modPath, CBTDIR, resPath, dietFilePath, abunFilePath, indInfoFilePath, objre, figForm, numWorkers, autoFix, compMod, rDiet, extSolve, fvaType, autorun);

**Pull request merged**
