### PR TITLE
Add opt knock tutorial

### PR DESCRIPTION
**Pull request by snmendoz**
[*I added the tutorial for optKnock and modified optKnock to remove unused lines and for handling inputs*]

**I hereby confirm that I have:**

- [ X] Tested my code on my own machine
- [ X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [ X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Thanks @snmendoz! Is `optKnockTutorial.m` a helper script, or is that the `.m` version of the tutorial?

Actually, the practice is that once a PR has been merged (or closed), the contributor creates a new branch using `contribute` and then selects option `[1]`. A PR for the branch `add-optKnockTutorial` had already been opened in PR #534 and has been closed as discussed. Now, the same [commit](https://github.com/snmendoz/cobratoolbox/commit/a3d3348bbc7f1b55710171557642bcbdbd6698f1) shows up in this PR together with other changes that have been pushed to the branch `add-optKnockTutorial`. That might also explain why you had some issues with `converToIrreversible.m`.

May you put in a new PR by selecting `[1]` in `contribute` and then committing your changes and tutorial? That would be perfect. Please let me know if you need assistance.

cc: @syarra

**Comment by snmendoz** [comment]
@laurentheirendt optKnockTutorial.m is the .m version of the tutorial (sort of)

I understand what you say. I will create new branches when the PR of a branch is closed. 

I don't undestand if I should open a new branch and
1) transfer the commits of this branch to the new branch, or
2) just put the files in the new branch and create a PR

**Comment by snmendoz** [comment]
I created the new PR #570
Regards,

**Comment by laurentheirendt** [comment]
Awesome! Thanks @snmendoz 👍 

In general, when using the devTools, it is easier to simply put the files in a new branch and create the PR (that's what you did). 

When using the terminal, you can *cherry-pick*, but that is more advanced `git` usage.

Closing this PR in favor or PR #570.

**Pull request closed without merging**
