### PR TITLE
Fix regulatory fba

### PR DESCRIPTION
**Pull request by tpfau**
When looking into the `solveBooleanRegModel` function, I noticed an odd call to `optimizeCbModel`:
`fbasolDR = optimizeCbModel(modelDR,'max',true);`
This call looks like it was originally intended to pass some flag as the third argument, but the third argument of optimizeCbModel is minNorm, and true (which matlab will interpret as a value of 1) will lead to a solution that, in addition to `osense*c` will minimize the quadratic fluxes of the solution with a weight of 1 for the quadratic fluxes. I think this is not what is supposed to happen here, where actually, the effect of the knockdown of several genes is the desired target.
I corrected this (in y opinion) obvious bug and adapted the test data accordingly.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Why did you completely remove `test/verifiedTests/analysis/testrFBA/refData_dynamicRFBA.mat`?

**Comment by tpfau** [comment]
its not completely removed. its only modified. 
otherwise that test would fail.

**Comment by laurentheirendt** [comment]
Ok, weird, Github indicates a 100% negative change, but maybe that's because it is a binary file. All good 👍

**Comment by laurentheirendt** [comment]
Thanks @tpfau 👍

**Pull request merged**
