### PR TITLE
Model merge without genes

### PR DESCRIPTION
**Pull request by tpfau**
Reintroduced model merging without gene related fields.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by rmtfleming** [comment]
This is urgent and it only affects one file, so why not merge it right away rather than adding the do not merge label?

**Comment by syarra** [comment]
Waiting for the  CI to complete its job!

**Comment by rmtfleming** [comment]
If Thomas has tested this function himself, there should be no issue.

**Comment by tpfau** [comment]
I agree with Sylvain that the CI should always be finishing its job, as this is the only way we have to be sure, that there are no unintended side effects. If someone urgently wants the changes he can cherry pick them to his/her copy without any issue. Or (in this instance) just do the minimal modification themselves, and stash the changes before updating again.

**Pull request merged**
