### PR TITLE
scripts related to INIT method

### PR DESCRIPTION
**Pull request by arichelle**

### CODE REVIEW

**Comment by laurentheirendt** [comment]
@arichelle , thank you. However, the documentation also has already been formatted here. May you follow the format that @jacekwachowiak implemented?

**Comment by laurentheirendt** [comment]
@arichelle, may you make the changes here as discussed? Thanks.

**Comment by rmtfleming** [comment]
@jacekwachowiak please would you

**Comment by laurentheirendt** [comment]
Thanks @arichelle 🌵

**Pull request merged**
