### PR TITLE
Testing alternative to MOCov

### PR DESCRIPTION
**Pull request by tpfau**
This is a test to try an alternative to MOCov since the matlab profiler sometimes looses Code Coverage.
It writes a valid cverage.json file which should be sufficient for CodeCov. This is just to test, whether this code cov calculation works.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Why not modify MoCov instead? https://github.com/uni-lu/MoCov

**Comment by tpfau** [comment]
Because from what I've seen when playing around a bit, is that the profiler sometimes "looses" code coverage data. 
Therefore, this modification extracts the profiling info after each individual test, and updates the coverage accordingly, which is something that the MoCov concept would not allow (running once). 
Also, this piece of code does not provide all facilities provided by MoCov (e.g. html output).

**Comment by laurentheirendt** [comment]
I prefer this code being either part of MoCov or in a separate repo so it can be reused in other repos.

**Comment by tpfau** [comment]
Well... I can try to move the whole testSuite part into a separate repo, because it is interconnected and can't really be separated.

**Comment by laurentheirendt** [comment]
What do you mean by `the whole testSuite part`?

**Comment by tpfau** [comment]
runTestSuite, runScript etc. This codecov is woven into it and not separate.

**Comment by laurentheirendt** [comment]
... hence my reasoning to actually modify MoCov. Moving the whole testSuite out is not a good idea.

**Comment by tpfau** [comment]
But as I said:
Modifying MoCov is not really an option, as it would not address the issue I want to address (profiler loosing info) at all.

**Comment by laurentheirendt** [comment]
But could we add this functionality then to MoCov?

**Pull request closed without merging**
