### PR TITLE
review of minimal cutsets tutorial

### PR DESCRIPTION
**Pull request by marouenbg**
[*Please include a short description of enhancement here*]

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [x] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by marouenbg** [comment]
@laurentheirendt could you put the in-progress label. Thanks.

**Comment by laurentheirendt** [comment]
@marouenbg, thank you for this. 

May you coordinate this with @susanGhaderi? She is currently working on this one. If you want to change a tutorial, you must change the `.mlx` file, and generate from there there the `.m`, `.pdf` `.html` files. Closing now.

**Comment by marouenbg** [comment]
@laurentheirendt could you open this PR back it is part of review and it is in progress.

**Comment by laurentheirendt** [comment]
May you open 1 PR per tutorial? That will help on my end. Thanks.

**Comment by laurentheirendt** [comment]
`tutorial_relaxFBA` is already updated in PR #702, originally from PR #664.

May you open a new PR for `tutorial_minimalCutSets`. Thanks. 🌵

**Pull request closed without merging**
