### PR TITLE
Adapted functions to newer versions of MATLAB

### PR DESCRIPTION
**Pull request by almut-heinken**
Adapted all instances of the readtable function in DEMETER and the Microbiome Modeling Toolbox to newer versions of Matlab. Made necessary changes in variable conversion.
Simplified some inputs.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by rmtfleming** [comment]
Please move the tests into a testDemeter folder inside of the cobratoolbox/test/additionalTests folder

**Comment by almut-heinken** [comment]
> Please move the tests into a testDemeter folder inside of the cobratoolbox/test/additionalTests folder

Hi Ronan, the test is for creation of pan-models, which fits better with the Microbiome Modeling Toolbox.

**Comment by rmtfleming** [comment]
Where is the code that tests the functionality of demeter?

**Comment by almut-heinken** [comment]
> Where is the code that tests the functionality of demeter?

I still need to write that function.  THat will be added at a later stage.

**Pull request merged**
