### PR TITLE
relaxFBA partial fix

### PR DESCRIPTION
**Pull request by rmtfleming**
[*Please include a short description of enhancement here*]

**I hereby confirm that I have:**

- [ x] Tested my code on my own machine
- [ x] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [ x] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by rmtfleming** [comment]
This is one to cherry pick. It is out of date with the devel as it was an old branch from a week ago without card opt recon x.

**Comment by tpfau** [comment]
What is this pr supposed to do? 
The change in the env-vars, will make this fail on all systems which use the default installation path, since it now looks for a non default location.
There is a style output change in printConstraints, which makes sense and we might actually think about in general changing %f and %e to %g, but there are no functional changes to relaxFBA (only the reordering of the docu, and a creation of an unused variable). 
Did you miss some commit here or accidentially created the wrong PR?

**Comment by rmtfleming** [comment]
I restarted on this branch, realising that I needed to be on a new, upto date branch of develop. The env-vars is a fix of something I already fixed already, why it is not in the master by now, I dont know. I am looking at the relaxFBA at the moment.

**Comment by tpfau** [comment]
The env-vars isn't in because this is something that is specific to your machine. On any other machine that used a default gurobi or other solver install, this will fail, so it was not merge with master, as it will fail for a majority of people.

> I restarted on this branch, realising that I needed to be on a new, upto date branch of develop. [...] I am looking at the relaxFBA at the moment.

But why did you put in a pr then, when you are still working on it?

**Comment by rmtfleming** [comment]
@laurentheirendt

**Pull request closed without merging**
