### PR TITLE
fixing curl for AntCore model

### PR DESCRIPTION
**Pull request by snmendoz**
[*I modified the url for obtaining the AntCore model. Also, I added -L to curl command to avoid redirection when communicating with github*]

**I hereby confirm that I have:**

- [ X] Tested my code on my own machine
- [ X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [ X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
@snmendoz, why exactly do you want to change the URL?

**Comment by snmendoz** [comment]
@laurentheirendt The group of Costas D. Maranas noticed that the model AntCore was not been downloaded when retrieveModels was run. I checked that and I confirmed that the model was not been downloaded. So, I changed the url to download the model. I also added a -L because it wasn't working otherwise. I also checked that the 12 other models were corrected downloaded as well using -L.

**Comment by laurentheirendt** [comment]
ok, but it shouldn't make a difference (unless rawgit.com wasn't online).

The advantage of the rawgit.com URL is that raw files are downloaded directly from GitHub with proper Content-Type headers.

**Comment by snmendoz** [comment]
this is the value of the variable "result_curl" when running line 54 of retrieveModels
`
[status_curl, result_curl] = system(['curl --max-time 15 -s -k --head ', modelArr{i, 2}]);

HTTP/2 200 
date: Tue, 04 Jul 2017 22:26:56 GMT
content-type: application/octet-stream
x-content-type-options: nosniff
x-robots-tag: none
access-control-allow-origin: *
etag: "ea814c2158c158c68fd52228abd73b855497d7e7"
cache-control: max-age=86400
vary: Accept-Encoding
rawgit-cache-status: HIT
server: NetDNA-cache/2.2
x-cache: HIT
`

**Comment by laurentheirendt** [comment]
Interesting. On my end:
```bash
$ curl --max-time 15 -s -k --head https://cdn.rawgit.com/snmendoz/Models/master/AntCore.mat
```
yields:
```
HTTP/1.1 200 OK
Date: Wed, 05 Jul 2017 02:13:01 GMT
Content-Type: application/octet-stream
Connection: keep-alive
X-Content-Type-Options: nosniff
X-Robots-Tag: none
Access-Control-Allow-Origin: *
ETag: "ea814c2158c158c68fd52228abd73b855497d7e7"
Cache-Control: max-age=86400
Vary: Accept-Encoding
RawGit-Cache-Status: HIT
Server: NetDNA-cache/2.2
X-Cache: MISS
```
The issue is with `OK` not being returned in the status. 

Anyway, I am fine with your proposed change. Thanks. 🎉

**Pull request merged**
