### PR TITLE
File io updates

### PR DESCRIPTION
**Pull request by tpfau**
This is a follow up of #462 
The SBML Binaries got updated and should no longer lead to the segfault experienced before.
Made a "default" minimum range of fields obtained from readCbModel. 

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by syarra** [comment]
Waoo! This is a long PR. I checked it quickly and  I didn't see anything odd. Thanks @tpfau 🎉 🏅

**Comment by tpfau** [comment]
Please have a look at getDefinedFieldProperties and the COBRAModelFields.xlsx. 
You said, that the style I haad for the model field definitions is not readable, so its now in an easily readable excel sheet.

**Comment by rmtfleming** [comment]
Hi Thomas,
please migrate COBRAModelFields.xlsx to a .m file with one line per field.
Regards,
Ronan

**Comment by tpfau** [comment]
No.
Such a file would be unmaintainable, i.e. it can't be edited in a sensible way (since there is no good formatting, that allows an easy overview of it).
If you want the corresponding data in matlab format there is the function getModelFieldDefinitions(), which will, depending on some inputs, return you a cell array with the respective data.

**Pull request merged**
