### PR TITLE
IO Update

### PR DESCRIPTION
**Pull request by tpfau**
Adjusting multiple IO Methods to properly handle multicharacter compartments.

Fixed a bug in SBML IO that allowed invalid Identifiers to be used for genes.

Corrected createModel to not add a default compartment, if there is already a multichar compartment id.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [] with [X] to check the box)*

### CODE REVIEW

**Comment by rmtfleming** [comment]
we need to make sure this support is propagated throughout the rest of the cobra toolbox where it is envisaged that [x] is the compartment rather than [xyz]?

**Comment by tpfau** [comment]
True. 
However, this is already used to some extend within the toolbox (e.g. getMultiSpeciesModelId uses an (almost) identical regexp to define the compartment in a species).
I think relaxing this constraint would in general allow for easier integration of multi-tissue and multi-species models, as the compartment-ID could contain the Tissue or species assignment. 
And it does not hurt any old things, as they are still perfectly valid.

**Comment by rmtfleming** [comment]
model.mets should be a primary key

**Comment by tpfau** [comment]
Could you elaborate what you mean?

**Comment by rmtfleming** [comment]
https://en.wikipedia.org/wiki/Unique_key

**Comment by tpfau** [comment]
I know what a primary key is.
But what do you want to say with this? 
mets will always be a primary key. and Duplicates wont be allowed. But I don't understand, why you mention it.

**Comment by tpfau** [comment]
done

**Pull request merged**
