### PR TITLE
Mat gpt

### PR DESCRIPTION
**Pull request by farid-zare**
MatGPT is added to cobraToolbox, as a subfolder of a new directory name chatGPT for future developments

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by rmtfleming** [comment]
Pls send an email to the cobra toolbox google group announcing this.

**Comment by tpfau** [comment]
Why wasn't this added as a submodule, which would make it a lot easier to keep it up to date with the current development in https://github.com/toshiakit/MatGPT ? Like this, the toolbox is essentially shipping an out of date version of the tool potentially overwriting a users installation of it...

**Comment by rmtfleming** [comment]
pls add as submodule

**Comment by farid-zare** [comment]
Thanks @tpfau for your comment.
Sure @rmtfleming will do now.

**Comment by farid-zare** [comment]
I believe we should revert this pull request

**Comment by farid-zare** [comment]
Pull request #2209 was made as a followup to this pull request

**Pull request merged**
