### PR TITLE
Handling of incompatibility R2016b - ILOGcomplex interface

### PR DESCRIPTION
**Pull request by laurentheirendt**
**Report issue:**

Direct API from ILOG and MATLAB R2016+ (releases `a` and `b`) are incompatible. 
Result is a crash of `MATLAB` - segmentation fault.

**Solution:**
Make `solveCobraLPCPLEX` throw an error when using MATLAB R2016+ and the `ILOGcomplex` interface.
Provide a suggestion to the user how to proceed.

### CODE REVIEW

**Comment by syarra** [comment]
Thanks @laurentheirendt for fixing this issue.

**Comment by rmtfleming** [comment]
Please inform IBM

**Comment by rmtfleming** [comment]
and Matlab

**Comment by laurentheirendt** [comment]
Just found out that IBM will release/released 12.7.0 (see [here](http://www-01.ibm.com/common/ssi/printableversion.wss?docURL=/common/ssi/rep_ca/2/897/ENUS216-482/index.html))- I will try that out to see if that fixes the incompatibility issue and will report back.

**Comment by laurentheirendt** [comment]
Update: IBM planned for Nov. 11, 2016, but 12.7.0 is not released yet.

**Comment by laurentheirendt** [comment]
`CPLEX 12.7.0` is not compatible with `R2016` (`a` or `b`). Issue reported.

**Pull request merged**
