### PR TITLE
Fix for issue #923

### PR DESCRIPTION
**Pull request by laurentheirendt**
Continuation of PR #924.

### CODE REVIEW

**Comment by tpfau** [comment]
Just as a reminder from the original PR: 
The fix needs to be restricted to the changeGeneAssociation function, as other functions depend on parseBoolean and altered output would make them fail.
As mentioned, the easiest is probably to run:
`rule = regexprep(rule,'x\(([0-9]+)\)','x(#$1)')` in line 66 of changeGeneAssociation (i.e. directly after parseBoolean was called).

**Comment by laurentheirendt** [comment]
@tpfau, may you work with @pauljensen to implement your suggested fix? Thanks 👍

**Comment by tpfau** [comment]
I would be happy to. but essentially its a very small change (reverting the changes to parseBoolean and adding the line I mentioned in changeGeneAssociation). 
If @pauljensen wants to implement it, feel free, otherwise I will create a fix that you can cherry-pick.

**Comment by laurentheirendt** [comment]
Maybe it is faster when you commit and I cherry-pick? Thanks.

**Comment by tpfau** [comment]
Commit `5d7af9b` from my pr924 branch should correct it.

**Comment by tpfau** [comment]
@laurentheirendt Could you check the fails here? Seems like some file is missing from the test models folder for some reason (i.e. the failing has nothing to do with the changes).

**Pull request merged**
