### PR TITLE
Reading Model Annotation from SBML files

### PR DESCRIPTION
**Pull request by tpfau**
Update to the SBML IO to properly read and write the model annotations.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Is there any way that we can add a few tests for these additions?

**Comment by tpfau** [comment]
Yes,
I'll have a look.

**Comment by tpfau** [comment]
I'm working on that now. But to make this a sensible check I will have to build a few functions for annotations (which can be reused when writing an SBML).

**Comment by tpfau** [comment]
Closing temporarily

**Pull request closed without merging**
