### PR TITLE
Borg name fixes

### PR DESCRIPTION
**Pull request by jtsauls**
This changes the name of functions in modelBorgifier which compete with native functions. The format for these files is functionBorg according to discussion in PR #949.

Additionally, an unused function was removed. 

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [] with [X] to check the box)*

### CODE REVIEW

**Comment by tpfau** [comment]
Looks fine for me. Could you try rebasing your branch, that might solve the failed test. 
The fail seems to be linked to problems in file IO, which are unrelated to your changes, and I know that @laurentheirendt did some fixes there recently.

**Comment by laurentheirendt** [comment]
No need to rebase. Thanks @tpfau and @jtsauls.

**Comment by tpfau** [comment]
@jtsauls Why did you close and delete the branch?

**Comment by jtsauls** [comment]
@tpfau Whoops, premature house cleaning.

**Pull request merged**
