### PR TITLE
Reconmap PR fix

### PR DESCRIPTION
**Pull request by bertonoronha**
ReconMap functions. Fixing the PR #1001 

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [x] Selected `develop` as a target branch (top left drop-down menu)

### CODE REVIEW

**Comment by tpfau** [comment]
The error on 2014b/2015b is due to contains only being introduced in 2016b.
simple replacement: `~isempty(regexp(str,pattern));`
In your case
`contains(response, '"status":"OK"')` would become:
`~isempty(regexp(response, '"status":"OK"'))`
No idea whats going wrong on the windows machines (or rather I'm not sure why it works on linux/mac but not on win).

**Comment by laurentheirendt** [comment]
@bertonoronha, may you rebase now this PR as PR #1010 is in? Then, you can proceed with implementing comments as @tpfau suggested on your PR #1001. Thanks 👍

**Comment by laurentheirendt** [comment]
@bertonoronha, may you fix this issue? Thanks! 👍 
```
10:44:05 Running testReconMap
10:44:10  > glpk is compatible and fully tested with MATLAB R2015b on your operating system.
10:44:19 
10:44:22 ================================================================================
10:44:22 Error occurred in testReconMap/testReconMap and it did not run to completion.
10:44:22 
10:44:27     --------------
10:44:27     Error Details:
10:44:27     --------------
10:44:27     Undefined function 'contains' for input arguments of type 'char'.
10:44:27     
10:44:27 ================================================================================
10:44:27 .
10:44:27 Done testReconMap
```

**Comment by tpfau** [comment]
See my comment above for a fix for this issue.
But I'm wondering what leads to the error on the windows machines (because thats something different).

**Comment by rmtfleming** [comment]
@bertonoronha this PR will not be merged till it works on windows

**Comment by tpfau** [comment]
Hi,
I had a look at this on a windows machine.
The reason for the windows error is the addition of the -H flag in `postMINERVArequest` on windows OS.
Not sure what it is intended to do, but removing it makes the test work.

**Comment by laurentheirendt** [comment]
What Windows machine did you test this on? The `-H` flag is required on Windows 10.

**Comment by tpfau** [comment]
A Win 7 machine.

**Comment by laurentheirendt** [comment]
Do you have somewhere a branch I can merge onto this one?

**Comment by tpfau** [comment]
just remove the `if ispc` block in `postMINERVArequest`. That was my fix....

**Comment by laurentheirendt** [comment]
@bertonoronha and @tpfau , so it seems that afterall, the `-H` flag wasn't required. The real fix was the replacement of special characters with their hexadecimal equivalent (as in [this](16e2866a0af0ba0a36a613714704c6474de7cf97) commit).

Thanks! 🎉

**Pull request merged**
