### PR TITLE
Fast-SL Algorithm

### PR DESCRIPTION
**Pull request by SomyaVerma27**
Updated and added fast-sl algorithm

**I hereby confirm that I have:**

- [x] Tested my code on my own machine
- [x] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [x] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by tpfau** [comment]
Could you rename the folder from "Synthetic Lethals" to `syntheticlethals` ?  
I guess there are several functions missing in the PR at the moment, (singleSL, doubeLS, tripleSL).
Is it intentional that the code saves its outputs to files instead of returning it from the call?

**Comment by SomyaVerma27** [comment]
Hi Thomas,

I have made the necessary changes.

**Review by rmtfleming — COMMENTED** [review]
http://opencobra.sourceforge.net/openCOBRA/Welcome.html is an old link, please update it to the new website.
Please move the tutorial to a corresponding folder within
https://github.com/opencobra/COBRA.tutorials
If the tutorial is generated as an .mlx file, then corresponding html version will be generated by us for the website
The .mat file for the tutorial can be added in that folder, unless it is already present in the cobra git environment?

**Comment by SomyaVerma27** [comment]
Moved tutorial to COBRA.tutorials.
I have opened a pull request in https://github.com/opencobra/COBRA.tutorials for the same change.
Find the pull request here: https://github.com/opencobra/COBRA.tutorials/pull/198

**Comment by SomyaVerma27** [comment]
Hi Ronan, Is there any update regarding this PR?

**Pull request merged**
