### PR TITLE
Updating Installation info wrt libssl

### PR DESCRIPTION
**Pull request by tpfau**
Some Matlab versions ship broken system libraries (in particular `libssl.so.1.0.0`) which need to be replaced by working ones in order to use webread without crashing matlab.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by tpfau** [comment]
We can put it in both places, but the problem is, that there is no error message (for the normal user). Matlab simply crashes without any comment.
If you are on a console, then you will get an error message, but not if you use the GUI.

**Comment by laurentheirendt** [comment]
Ok, but then the crash behavior should be mentioned in the FAQ. 

You can include a link in the `requirements` section to the `FAQ`.

**Comment by tpfau** [comment]
closing temporarily

**Comment by tpfau** [comment]
Reopening

**Comment by laurentheirendt** [comment]
Closing. See #1278.

**Pull request closed without merging**
