### PR TITLE
Updated Microbiome Modeling Toolbox

### PR DESCRIPTION
**Pull request by almut-heinken**
This is addressing the comments on my previous pull request https://github.com/opencobra/cobratoolbox/pull/1124.
Also, further functionalities have been added.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [] with [X] to check the box)*

### CODE REVIEW

**Comment by tpfau** [comment]
Could you commit these changes based on the old PR ? 
That would make it much easier to track what was now altered

**Comment by tpfau** [comment]
@laurentheirendt is that possible with the devTools ?

**Comment by akaviaLab** [comment]
I think you can just keep editing on the same branch as the old PR, and then push it to GitHub.

**Comment by laurentheirendt** [comment]
Merged into #1124.

@almut-heinken, may you check that everything is as it should? Thanks 👍

**Comment by almut-heinken** [comment]
@laurentheirendt Thanks! Everything looks OK. I fixed a few extra issues that came up in the meantime directly in the pull request.

**Pull request closed without merging**
