### PR TITLE
IO Tutorial and IO Update

### PR DESCRIPTION
**Pull request by tpfau**
IOTutorial added and the IO is updated to be much more flexible when loading models.
Also added a checkModel() function - needs to be updated at some point to actually represent the required/optional fields, currently only a subset is used.

read and writeCbModel are adapted to accept parameter value pairs and to allow Excel and matlab IO (i.e. you can load models from mat files). I.e. all model IO can no go through these functions (no more xls2model etc).
Set a definition for Excel format models and their IO (could be updated in the future)
The latter functionality depends on the model struct and currently only those with required fields present will be loaded. This again depends on the definition of those fields and is currently saved in getDefinedFieldProperties (the function will have to be adapted to the new field definitions in the future).
Moved the mps io from writeCbModel to writeLPProblem (the old convertCobraLP2mps is changed to that function) and updated the respective tests. 
Also updated the tests for printRxnFormula/printFluxVector to reflect the change in printRxnFormula (irreversible reactions are no longer determined by "rev" but by lower bounds.

**I hereby confirm that I have:**

- [X] Selected `develop` as a target branch (top left drop-down menu)
- [X] Tested my code on my own machine 
- [X] Followed the guidelines in the [Contributing Guide](https://github.com/opencobra/cobratoolbox/blob/master/.github/CONTRIBUTING.md)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by tpfau** [comment]
Closing in favor of

**Comment by rmtfleming** [comment]
Please also include your tutorial in .m and .pdf formats derived from the .mlx so web users can see the content as .mlx files appear "binary" to git.

**Comment by rmtfleming** [comment]
Hi Thomas,
please put the verification scripts into 
modelGeneration/modelVerification
Regards,
Ronan

**Comment by tpfau** [comment]
closing in favor of [420](https://github.com/opencobra/cobratoolbox/pull/420)

**Pull request closed without merging**
