### PR TITLE
fixing comments of optforce functions

### PR DESCRIPTION
**Pull request by snmendoz**
[*Fixing commentaries in OptForce functions*]

**I hereby confirm that I have:**

- [X ] Tested my code on my own machine
- [X ] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X ] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by laurentheirendt** [comment]
@snmendoz, I rebased this PR, solved all conflicts, and formatted the files in the `optForce` folder. I also added the required `.rst` files for automatic documentation generation.

May you format the files in the `optForceGAMS` folder in the same way? That would really help.

I also saw that there was a duplicated of `FVAOptForce.m` - I removed it.

**Comment by snmendoz** [comment]
This PR should be closed in favor of PR #523

**Comment by laurentheirendt** [comment]
@snmendoz, I did some substantial changes to make the documentation build automatically. This PR should not be closed. I also added the required `.rst` files for automatic documentation generation.

May you format the files in the `optForceGAMS` folder in the same way? That would really help. Thanks.

**Comment by snmendoz** [comment]
Oh sorry, I didn't realize that you had made such progress. I was only thinking that these functions were obsolete since I uploaded new functions in PR 523 

To summarize, you:
1) remove ":" from description of inputs/outputs (in the documentation section). E.g.
`%    constrW:       (structure) structure containing contraints`
 
instead of 

`%    constrW:       Type: structure
 %                   Description: structure containing contraints`

2) remove spaces at the end of each line
3) remove accent marks
4) put [] = in case that a function don't return any variable
5) added .rst files

I can perform the same tasks in the folder optForceGAMS, as you suggest. Should I perform the changes in this PR or in another PR? I am just wondering if there wouldn't be any trouble with the new functions 
 I uploaded in PR 523. 

should I add .rst files too?

**Comment by laurentheirendt** [comment]
@snmendoz, no worries. Apart from the spaces at the end of each line (which are actually removed automatically when using the [ATOM editor](www.atom.io)), that list seems so summarize well the changes I made.

It would be nice if you could continue pushing on this PR. You can add the `.rst` file if you want.

Thanks for helping out! 👍

**Comment by laurentheirendt** [comment]
@snmendoz, do you need my help here?

**Comment by snmendoz** [comment]
@laurentheirendt  How are we with the timing? I think I can finish this PR during the weekend. If you prefer to make progress before the weekend, I think I will need your help

**Comment by laurentheirendt** [comment]
No worries. Let's try to finish this PR up next week. Thanks @snmendoz.

**Comment by syarra** [comment]
@snmendoz, how are things going for this PR?
Do you need my help?

**Comment by snmendoz** [comment]
@syarra yes, thank you. I have two questions. 
1) how do I generate .rst files? Is there a guideline to create this type of files?
2) The updated functions for running optForce are already merged in the master branch of cobra toolbox. In this PR I have old versions of those functions, so how can we avoid to damage the updated functions when this PR will be accepted for merging?

I think I will finish this PR

**Comment by laurentheirendt** [comment]
@snmendoz, this PR needs rebasing (don't worry about that). 

What other .rst files are needed? They are simple text files; there is no guideline for generating these as this is generally only done once. If you want, you can duplicate an existing .rst file and edit it.

**Comment by snmendoz** [comment]
@laurentheirendt so no other .rst files is needed? Perfect then. I will just concentrate on my functions

**Comment by laurentheirendt** [comment]
Yes, no other .rst files are needed. Just concentrate on the headers of your functions - the rebase will be done after that.

**Comment by snmendoz** [comment]
@laurentheirendt It was a lot of tedious work but it's finally done. 

Let me know if additional changes are required.

Best,

**Comment by snmendoz** [comment]
@laurentheirendt do you need additional help here?

**Comment by laurentheirendt** [comment]
Thanks @snmendoz for offering your help. Just one question: if I understand correctly, the body of the functions in this PR should not be changed, only the documentation. Am I right?

**Comment by snmendoz** [comment]
The body of the functions that are currently in the master branch should not be changed. Just the documentation of the before mentioned functions should be changed. 

Please note that I created a new PR which include the suggestions made by the group of Costas D. Maranas. In that PR I changed the body of the functions (a lot of change) as well as the documentation (just a little)

**Comment by laurentheirendt** [comment]
Ok. We will merge PR #665 first. Then, we can try to save the documentation on this PR ...

**Comment by laurentheirendt** [comment]
Closing in favor of PR #669. Thanks @snmendoz.

**Pull request closed without merging**
