### PR TITLE
Find exc reaction update

### PR DESCRIPTION
**Pull request by tpfau**
Altered findExcReaction to also find Exchangers with non 1/-1 values and return all exchange reactions, that can transport compounds into the system as uptakes.

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [X] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [] with [X] to check the box)*

### CODE REVIEW

**Comment by rmtfleming** [comment]
findExcReaction is a duplicate of the function model = findSExRxnInd(model, nRealMet, printLevel)
 and the former should be deleted, or all code deleted and a wrapper maintained.

**Comment by tpfau** [comment]
I would contradict that.
For one, findSExcRxnInd always includes the objective reaction in the set of Exchange Reactions indicated (while it's not necessarily an exchanger).
Also, findSExRxns uses a lot of heuristics that might (or might not) be correct for identification of Exchange reactions (sink_, DM_, EX_), while findExcReaction relies purely on the definition of an Exchanger as a single non zero entry in the S matrix, 
These are options findExRxnsInd does not offer, so it is not doing the same.

**Comment by laurentheirendt** [comment]
@tpfau, may you rebase your branch? Some tests are failing, but these issues have been fixed in the meantime. Thanks 👍

**Comment by laurentheirendt** [comment]
@tpfau, may you make the changes here as discussed? Thanks.

**Comment by rmtfleming** [comment]
Not strictly a duplicate, but my point is the same, they both approach pretty much the same task. findExcRxns.m should be kept as a shell wrapper calling findSExRxnInd.m which should be extended with an option to elicit whatever aditional functionality findExcRxns.m.

**Comment by tpfau** [comment]
This was done in 1d67ab6 and 6c047b5
The only thing that I did not move to `findSExRxnInd` is the check for the objective function, which (imo) doesn't make any sense in `findSExRxnInd` as it would introduce functionality, that has nothing to do with finding exchange reactions (and which I would only keep in the function for backward copatability)

**Pull request closed without merging**
