### PR TITLE
debug_testCreatePanModelsm

### PR DESCRIPTION
**Pull request by rosieluo2021**
*Please include a short description of enhancement here*

**I hereby confirm that I have:**

- [X] Tested my code on my own machine
- [ ] Followed the guidelines in the [Contributing Guide](https://opencobra.github.io/cobratoolbox/docs/contributing.html)
- [X] Selected `develop` as a target branch (top left drop-down menu)

*(Note: You may replace [ ] with [X] to check the box)*

### CODE REVIEW

**Comment by farid-zare** [comment]
Hi Rosie,
Thanks for your contribution.
I think we can't add a user prompt section in test functions such as the one you added to the "testCreatePanModels.m". As the tests are going to be part of an automated continues integration, there should be no user prompt requirement for running a test. I think we have to revert that commit until we find a better solution for panModels testing.

**Comment by rosieluo2021** [comment]
Hi Farid,

Ok, no problem. I thought the user should check the non growing models
manually, that’s why I changed like that. You can ignore any unsuitable
comments, thanks~

Regards,
Xi

Farid Zare ***@***.***>于2024年10月5日 周六16:40写道：

**Comment by rmtfleming** [comment]
resolve conflicts

**Comment by farid-zare** [comment]
Changes to "testCreatePanModels" are not confirmed and should be removed. 
Almut is working on "testCreatePanModels" to resolve its problem

commit b8c9d66c3cb0a9b60f8404fe8ca4fe3c6dc7a959 should be removed.

**Pull request closed without merging**
